### ISSUE TITLE
Post baseline scenario for VNM, WLD, USA variables

### ISSUE THREAD

**Issue by jaromir-benes** [OGResearch/escap-vnm#1]

**Comment by AnnaAugusztin** [comment]
some of the VNM variables are exogenous and not forecasted via the model: for example we are using population or working age population forecasts from UN. So in the raw datafile we have data for these variables until the end of the fcast horizon. 

I assume it is important for you to know which variables are exogenous in this sense, so I also added results_raw.csv, which contains the VNM raw data.
